### ISSUE TITLE
XML or text declaration not at start of entity: line 25, column 0

### ISSUE THREAD

**Issue by ccs-ros** [uzh-rpg/dslam_open#1]
when i run the command "catkin build",it appeared.i don't know what is the meaning?And where is the "runDistributedMapper",where is the "feature/logging"?i can't find these.mybe i make a mistake when installed.i can't run the simulation!please give me some advice,thank you!

**Comment by ccs-ros** [comment]
the error message is here:
Profile:                     default
Extending:        [explicit] /opt/ros/jade
Workspace:                   /home/ccs/my_ws
-------------------------------------------------------
Source Space:       [exists] /home/ccs/my_ws/src
Log Space:         [missing] /home/ccs/my_ws/logs
Build Space:        [exists] /home/ccs/my_ws/build
Devel Space:        [exists] /home/ccs/my_ws/devel
Install Space:      [unused] /home/ccs/my_ws/install
DESTDIR:            [unused] None
-------------------------------------------------------
Devel Space Layout:          merged
Install Space Layout:        None
-------------------------------------------------------
Additional CMake Args:       -DCMAKE_BUILD_TYPE=Release
Additional Make Args:        None
Additional catkin Make Args: None
Internal Make Job Server:    True
Cache Job Environments:      False
-------------------------------------------------------
Whitelisted Packages:        None
Blacklisted Packages:        None
-------------------------------------------------------
Workspace configuration appears valid.
-------------------------------------------------------
Traceback (most recent call last):
  File "/usr/bin/catkin", line 9, in <module>
    load_entry_point('catkin-tools==0.4.4', 'console_scripts', 'catkin')()
  File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 267, in main
    catkin_main(sysargs)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 262, in catkin_main
    sys.exit(args.main(args) or 0)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/cli.py", line 420, in main
    summarize_build=opts.summarize  # Can be True, False, or None
  File "/usr/lib/python2.7/dist-packages/catkin_tools/verbs/catkin_build/build.py", line 283, in build_isolated_workspace
    workspace_packages = find_packages(context.source_space_abs, exclude_subspaces=True, warnings=[])
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 86, in find_packages
    packages = find_packages_allowing_duplicates(basepath, exclude_paths=exclude_paths, exclude_subspaces=exclude_subspaces, warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 146, in find_packages_allowing_duplicates
    xml, filename=filename, warnings=warnings)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/package.py", line 502, in parse_package_string
    raise InvalidPackage('The manifest contains invalid XML:\n%s' % ex)
catkin_pkg.package.InvalidPackage: The manifest contains invalid XML:
XML or text declaration not at start of entity: line 25, column 0

**Comment by yanjundream** [comment]
I have encountered the same error and solved it by simply remove the lines before line 25 in that file. There are also another two files having the same error. Besides these, you will encounter other three errors to make a successful build. I listed them here and show the solutions I used. 


1. xml error: remove declaration in .xml
2. opencv/nonfree/.hpp error:

`sudo add-apt-repository --yes ppa:xqms/opencv-nonfree`
`sudo apt-get update `
`sudo apt-get install libopencv-nonfree-dev`

3. ./autogen.sh: 38: ./autogen.sh: autoreconf: not found

`sudo apt-get install autoconf`

4.  Could NOT find GLEW
`sudo apt-get install libglew-dev`

**Comment by ccs-ros** [comment]
@yanjundream thank you! I solved my problem by using your method.And during the installation process,still encountered many error message.the final message is:

Failed     << ceres_catkin:make                   [ Exited with code 2 ]       
Failed    <<< ceres_catkin                        [ 6 minutes and 22.5 seconds ]
[build] Summary: 9 of 18 packages succeeded.                                   
[build]   Ignored:   None.                                                     
[build]   Warnings:  1 packages succeeded with warnings.                       
[build]   Abandoned: 7 packages were abandoned.                                
[build]   Failed:    2 packages failed.                                        
[build] Runtime: 6 minutes and 23.4 seconds total.     

Does this mean that the installation was successful?

**Comment by ccs-ros** [comment]
the error message is here:
/home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/include/DUtilsCV/Drawing.h:420:7: error: ‘line’ is not a member of ‘cv’
       cv::line(m_canvas, a, b, style.color, style.thickness);
       ^
/home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/include/DUtilsCV/Drawing.h:427:5: error: ‘circle’ is not a member of ‘cv’
     cv::circle(m_canvas, cv::Point(toPxX(x[0]), toPxY(y[0])), 1, 
     ^
In file included from /home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/include/DUtilsCV/IO.h:17:0,
                 from /home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/include/DUtilsCV/DUtilsCV.h:47,
                 from /home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/FSolver.cpp:17:
/usr/include/opencv2/legacy/legacy.hpp: At global scope:
/usr/include/opencv2/legacy/legacy.hpp:1750:53: error: ‘cv::EM’ has not been declared
     CvEMParams( int nclusters, int cov_mat_type=cv::EM::COV_MAT_DIAGONAL,
                                                     ^
/usr/include/opencv2/legacy/legacy.hpp:1751:36: error: ‘cv::EM’ has not been declared
                 int start_step=cv::EM::START_AUTO_STEP,
                                    ^
/usr/include/opencv2/legacy/legacy.hpp:1767:1: error: expected class-name before ‘{’ token
 {
 ^
/usr/include/opencv2/legacy/legacy.hpp:1770:34: error: ‘cv::EM’ has not been declared
     enum { COV_MAT_SPHERICAL=cv::EM::COV_MAT_SPHERICAL,
                                  ^
/usr/include/opencv2/legacy/legacy.hpp:1771:34: error: ‘cv::EM’ has not been declared
            COV_MAT_DIAGONAL =cv::EM::COV_MAT_DIAGONAL,
                                  ^
/usr/include/opencv2/legacy/legacy.hpp:1772:34: error: ‘cv::EM’ has not been declared
            COV_MAT_GENERIC  =cv::EM::COV_MAT_GENERIC };
                                  ^
/usr/include/opencv2/legacy/legacy.hpp:1775:29: error: ‘cv::EM’ has not been declared
     enum { START_E_STEP=cv::EM::START_E_STEP,
                             ^
/usr/include/opencv2/legacy/legacy.hpp:1776:29: error: ‘cv::EM’ has not been declared
            START_M_STEP=cv::EM::START_M_STEP,
                             ^
/usr/include/opencv2/legacy/legacy.hpp:1777:32: error: ‘cv::EM’ has not been declared
            START_AUTO_STEP=cv::EM::START_AUTO_STEP };
                                ^
/usr/include/opencv2/legacy/legacy.hpp:1825:9: error: ‘EM’ in namespace ‘cv’ does not name a type
     cv::EM emObj;
         ^
/usr/include/opencv2/legacy/legacy.hpp: In member function ‘double CvEM::getLikelihood() const’:
/usr/include/opencv2/legacy/legacy.hpp:1807:58: error: ‘emObj’ was not declared in this scope
     CV_WRAP inline double getLikelihood() const { return emObj.isTrained() ? logLikelihood : DBL_MAX; }
                                                          ^
/usr/include/opencv2/legacy/legacy.hpp: At global scope:
/usr/include/opencv2/legacy/legacy.hpp:2622:1: error: expected class-name before ‘{’ token
 {
 ^
/usr/include/opencv2/legacy/legacy.hpp:2667:17: error: ‘GenericDescriptorMatcher’ was not declared in this scope
     virtual Ptr<GenericDescriptorMatcher> clone( bool emptyTrainData=false ) const;
                 ^
/usr/include/opencv2/legacy/legacy.hpp:2667:41: error: template argument 1 is invalid
     virtual Ptr<GenericDescriptorMatcher> clone( bool emptyTrainData=false ) const;
                                         ^
/usr/include/opencv2/legacy/legacy.hpp:2695:1: error: expected class-name before ‘{’ token
 {
 ^
/usr/include/opencv2/legacy/legacy.hpp:2736:17: error: ‘GenericDescriptorMatcher’ was not declared in this scope
     virtual Ptr<GenericDescriptorMatcher> clone( bool emptyTrainData=false ) const;
                 ^
/usr/include/opencv2/legacy/legacy.hpp:2736:41: error: template argument 1 is invalid
     virtual Ptr<GenericDescriptorMatcher> clone( bool emptyTrainData=false ) const;
                                         ^
/usr/include/opencv2/legacy/legacy.hpp:2927:38: error: variable or field ‘cvInitSubdivDelaunay2D’ declared void
 CVAPI(void)  cvInitSubdivDelaunay2D( CvSubdiv2D* subdiv, CvRect rect );
                                      ^
/usr/include/opencv2/legacy/legacy.hpp:2927:38: error: ‘CvSubdiv2D’ was not declared in this scope
/usr/include/opencv2/legacy/legacy.hpp:2927:50: error: ‘subdiv’ was not declared in this scope
 CVAPI(void)  cvInitSubdivDelaunay2D( CvSubdiv2D* subdiv, CvRect rect );
                                                  ^
/usr/include/opencv2/legacy/legacy.hpp:2927:65: error: expected primary-expression before ‘rect’
 CVAPI(void)  cvInitSubdivDelaunay2D( CvSubdiv2D* subdiv, CvRect rect );
                                                                 ^
In file included from /usr/local/include/opencv2/core/core_c.h:48:0,
                 from /usr/local/include/opencv/cv.h:63,
                 from /home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/FSolver.cpp:13:
/usr/include/opencv2/legacy/legacy.hpp:2930:1: error: ‘CvSubdiv2D’ does not name a type
 CVAPI(CvSubdiv2D*)  cvCreateSubdiv2D( int subdiv_type, int header_size,
 ^
In file included from /home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/include/DUtilsCV/IO.h:17:0,
                 from /home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/include/DUtilsCV/DUtilsCV.h:47,
                 from /home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/FSolver.cpp:17:
/usr/include/opencv2/legacy/legacy.hpp:2937:12: error: ‘CvSubdiv2D’ does not name a type
 CV_INLINE  CvSubdiv2D* cvCreateSubdivDelaunay2D( CvRect rect, CvMemStorage* storage )
            ^
In file included from /usr/local/include/opencv2/core/core_c.h:48:0,
                 from /usr/local/include/opencv/cv.h:63,
                 from /home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/FSolver.cpp:13:
/usr/include/opencv2/legacy/legacy.hpp:2948:1: error: ‘CvSubdiv2DPoint’ does not name a type
 CVAPI(CvSubdiv2DPoint*)  cvSubdivDelaunay2DInsert( CvSubdiv2D* subdiv, CvPoint2D32f pt);
 ^
/usr/include/opencv2/legacy/legacy.hpp:2953:1: error: ‘CvSubdiv2DPointLocation’ does not name a type
 CVAPI(CvSubdiv2DPointLocation)  cvSubdiv2DLocate(
 ^
In file included from /home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/include/DUtilsCV/IO.h:17:0,
                 from /home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/include/DUtilsCV/DUtilsCV.h:47,
                 from /home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/FSolver.cpp:17:
/usr/include/opencv2/legacy/legacy.hpp:2959:37: error: variable or field ‘cvCalcSubdivVoronoi2D’ declared void
 CVAPI(void)  cvCalcSubdivVoronoi2D( CvSubdiv2D* subdiv );
                                     ^
/usr/include/opencv2/legacy/legacy.hpp:2959:37: error: ‘CvSubdiv2D’ was not declared in this scope
/usr/include/opencv2/legacy/legacy.hpp:2959:49: error: ‘subdiv’ was not declared in this scope
 CVAPI(void)  cvCalcSubdivVoronoi2D( CvSubdiv2D* subdiv );
                                                 ^
/usr/include/opencv2/legacy/legacy.hpp:2963:38: error: variable or field ‘cvClearSubdivVoronoi2D’ declared void
 CVAPI(void)  cvClearSubdivVoronoi2D( CvSubdiv2D* subdiv );
                                      ^
/usr/include/opencv2/legacy/legacy.hpp:2963:38: error: ‘CvSubdiv2D’ was not declared in this scope
/usr/include/opencv2/legacy/legacy.hpp:2963:50: error: ‘subdiv’ was not declared in this scope
 CVAPI(void)  cvClearSubdivVoronoi2D( CvSubdiv2D* subdiv );
                                                  ^
In file included from /usr/local/include/opencv2/core/core_c.h:48:0,
                 from /usr/local/include/opencv/cv.h:63,
                 from /home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/FSolver.cpp:13:
/usr/include/opencv2/legacy/legacy.hpp:2967:1: error: ‘CvSubdiv2DPoint’ does not name a type
 CVAPI(CvSubdiv2DPoint*) cvFindNearestPoint2D( CvSubdiv2D* subdiv, CvPoint2D32f pt );
 ^
In file included from /home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/include/DUtilsCV/IO.h:17:0,
                 from /home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/include/DUtilsCV/DUtilsCV.h:47,
                 from /home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/FSolver.cpp:17:
/usr/include/opencv2/legacy/legacy.hpp:2972:12: error: ‘CvSubdiv2DEdge’ does not name a type
 CV_INLINE  CvSubdiv2DEdge  cvSubdiv2DNextEdge( CvSubdiv2DEdge edge )
            ^
/usr/include/opencv2/legacy/legacy.hpp:2978:12: error: ‘CvSubdiv2DEdge’ does not name a type
 CV_INLINE  CvSubdiv2DEdge  cvSubdiv2DRotateEdge( CvSubdiv2DEdge edge, int rotate )
            ^
/usr/include/opencv2/legacy/legacy.hpp:2983:12: error: ‘CvSubdiv2DEdge’ does not name a type
 CV_INLINE  CvSubdiv2DEdge  cvSubdiv2DSymEdge( CvSubdiv2DEdge edge )
            ^
/usr/include/opencv2/legacy/legacy.hpp:2988:12: error: ‘CvSubdiv2DEdge’ does not name a type
 CV_INLINE  CvSubdiv2DEdge  cvSubdiv2DGetEdge( CvSubdiv2DEdge edge, CvNextEdgeType type )
            ^
/usr/include/opencv2/legacy/legacy.hpp:2996:12: error: ‘CvSubdiv2DPoint’ does not name a type
 CV_INLINE  CvSubdiv2DPoint*  cvSubdiv2DEdgeOrg( CvSubdiv2DEdge edge )
            ^
/usr/include/opencv2/legacy/legacy.hpp:3003:12: error: ‘CvSubdiv2DPoint’ does not name a type
 CV_INLINE  CvSubdiv2DPoint*  cvSubdiv2DEdgeDst( CvSubdiv2DEdge edge )
            ^
/usr/include/opencv2/legacy/legacy.hpp:3014:29: error: variable or field ‘icvDrawMosaic’ declared void
 CVAPI(void)  icvDrawMosaic( CvSubdiv2D* subdiv, IplImage* src, IplImage* dst );
                             ^
/usr/include/opencv2/legacy/legacy.hpp:3014:29: error: ‘CvSubdiv2D’ was not declared in this scope
/usr/include/opencv2/legacy/legacy.hpp:3014:41: error: ‘subdiv’ was not declared in this scope
 CVAPI(void)  icvDrawMosaic( CvSubdiv2D* subdiv, IplImage* src, IplImage* dst );
                                         ^
/usr/include/opencv2/legacy/legacy.hpp:3014:57: error: expected primary-expression before ‘*’ token
 CVAPI(void)  icvDrawMosaic( CvSubdiv2D* subdiv, IplImage* src, IplImage* dst );
                                                         ^
/usr/include/opencv2/legacy/legacy.hpp:3014:59: error: ‘src’ was not declared in this scope
 CVAPI(void)  icvDrawMosaic( CvSubdiv2D* subdiv, IplImage* src, IplImage* dst );
                                                           ^
/usr/include/opencv2/legacy/legacy.hpp:3014:72: error: expected primary-expression before ‘*’ token
 CVAPI(void)  icvDrawMosaic( CvSubdiv2D* subdiv, IplImage* src, IplImage* dst );
                                                                        ^
/usr/include/opencv2/legacy/legacy.hpp:3014:74: error: ‘dst’ was not declared in this scope
 CVAPI(void)  icvDrawMosaic( CvSubdiv2D* subdiv, IplImage* src, IplImage* dst );
                                                                          ^
/usr/include/opencv2/legacy/legacy.hpp:3018:32: error: ‘CvSubdiv2D’ was not declared in this scope
 CVAPI(int)   icvSubdiv2DCheck( CvSubdiv2D* subdiv );
                                ^
/usr/include/opencv2/legacy/legacy.hpp:3018:44: error: ‘subdiv’ was not declared in this scope
 CVAPI(int)   icvSubdiv2DCheck( CvSubdiv2D* subdiv );
                                            ^
/home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/BRIEF.cpp: In member function ‘void DVision::BRIEF::compute(const cv::Mat&, const std::vector<cv::KeyPoint>&, std::vector<boost::dynamic_bitset<> >&, bool) const’:
/home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/BRIEF.cpp:54:7: error: ‘cvtColor’ is not a member of ‘cv’
       cv::cvtColor(image, aux, CV_RGB2GRAY);
       ^
/home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/BRIEF.cpp:61:5: error: ‘GaussianBlur’ is not a member of ‘cv’
     cv::GaussianBlur(aux, im, ksize, sigma, sigma);
     ^
/home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/ImageFunctions.cpp: In static member function ‘static cv::Mat DVision::ImageFunctions::getPatch(const cv::Mat&, const cv::KeyPoint&, int, bool, bool)’:
/home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/ImageFunctions.cpp:44:19: error: ‘getRotationMatrix2D’ is not a member of ‘cv’
     cv::Mat rot = cv::getRotationMatrix2D(
                   ^
/home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/ImageFunctions.cpp:48:5: error: ‘warpAffine’ is not a member of ‘cv’
     cv::warpAffine(patch, r_patch, rot, cv::Size(patch.rows, patch.cols),
     ^
/home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/ImageFunctions.cpp:49:7: error: ‘INTER_AREA’ is not a member of ‘cv’
       cv::INTER_AREA);
       ^
/home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/ImageFunctions.cpp:69:5: error: ‘resize’ is not a member of ‘cv’
     cv::resize(p1, ret, cv::Size(final_size, final_size), cv::INTER_AREA);
     ^
/home/ccs/catkin_ws/build/dlib_catkin/dlib_src-prefix/src/dlib_src/src/DVision/ImageFunctions.cpp:69:59: error: ‘INTER_AREA’ is not a member of ‘cv’
     cv::resize(p1, ret, cv::Size(final_size, final_size), cv::INTER_AREA);
                                                           ^
this is the problem of opencv ?

**Comment by ccs-ros** [comment]
@yanjundream my opencv version is 3.1.0

**Comment by yanjundream** [comment]
I have checked my opencv version and it is '2.4.8'. I have compiled all 18 packages successfully and I guess this means right. I suggested you use a pure ubuntu14 virtual machine to try first. Then come back to solve your version confliction problem.

**Comment by ccs-ros** [comment]
@yanjundream I used the pure ubuntu14.04 to try again,and can't git clone something:
Errors     << ceres_catkin:make /home/ccs/my_ws/logs/ceres_catkin/build.make.005.log
CMake Error at /home/ccs/my_ws/build/ceres_catkin/ceres_src-prefix/tmp/ceres_src-gitclone.cmake:40 (message):
  Failed to clone repository:
  'https://ceres-solver.googlesource.com/ceres-solver'


make[2]: *** [ceres_src-prefix/src/ceres_src-stamp/ceres_src-download] Error 1
make[1]: *** [CMakeFiles/ceres_src.dir/all] Error 2
make: *** [all] Error 2
is this the problem of my network?or something else?

**Comment by Gaoee** [comment]
you can change “https://ceres-solver.googlesource.com/ceres-solver“ to ”https://github.com/ceres-solver/ceres-solver.git”

**Comment by ccs-ros** [comment]
@Gaoee thank you! i solved my problem. And the message means well? here is some warning.

Warnings   << ceres_catkin:make /home/ccs/my_ws/logs/ceres_catkin/build.make.007.log
-- Found Eigen version 3.2.10: /home/ccs/my_ws/devel/include/eigen3

   ===============================================================
   Disabling the use of Eigen as a sparse linear algebra library.
   This does not affect the covariance estimation algorithm 
   which can still use the EIGEN_SPARSE_QR algorithm.
   ===============================================================

-- Found LAPACK library: /usr/lib/liblapack.so;/usr/lib/libblas.so
-- Found BLAS library: /usr/lib/libblas.so
-- Failed to find SuiteSparse - Did not find AMD library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find AMD header (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CAMD library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CAMD header (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find COLAMD library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find COLAMD header (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CCOLAMD library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CCOLAMD header (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CHOLMOD library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find CHOLMOD header (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find SuiteSparseQR library (required SuiteSparse component).
-- Failed to find SuiteSparse - Did not find SUITESPARSEQR header (required SuiteSparse component).
-- Failed to find SuiteSparse - Failed to find either: SuiteSparse_config header & library (should be present in all SuiteSparse >= v4 installs), or UFconfig header (should be present in all SuiteSparse < v4 installs).
-- Did not find all SuiteSparse dependencies, disabling SuiteSparse support.
-- Failed to find CXSparse - Could not find CXSparse include directory, set CXSPARSE_INCLUDE_DIR to directory containing cs.h
-- Did not find CXSparse, Building without CXSparse.
   ===============================================================
   Compiling without any sparse library: SuiteSparse, CXSparse 
   & Eigen (Sparse) are all disabled or unavailable.  No sparse 
   linear solvers (SPARSE_NORMAL_CHOLESKY & SPARSE_SCHUR)
   will be available when Ceres is used.
   ===============================================================
-- Found Google Flags header in: /home/ccs/my_ws/devel/include, in namespace: google
-- Found Google Log (glog). Assuming glog was built with gflags support as gflags was found. This will make gflags a public dependency of Ceres.
-- Building with OpenMP.
-- Found tr1/unordered_map/set in std::tr1 namespace.
-- Found shared_ptr in std::tr1 namespace using <tr1/memory> header.
-- Building Ceres as a shared library.
-- Do not build any example.
CMake Warning:
  Manually-specified variables were not used by the project:

    CMAKE_EXPORT_NO_PACKAGE_REGISTRY


make[3]: warning: -jN forced in submake: disabling jobserver mode.
make[3]: warning: -jN forced in submake: disabling jobserver mode.
cd /home/ccs/my_ws/build/ceres_catkin; catkin build --get-env ceres_catkin | catkin env -si  /usr/bin/make --jobserver-fds=6,7 -j; cd -
...............................................................................
Finished  <<< ceres_catkin                        [ 3 minutes and 27.6 seconds ]
Starting  >>> dslam                                                            
Finished  <<< dslam                               [ 10.4 seconds ]             
[build] Summary: All 18 packages succeeded!                                    
[build]   Ignored:   None.                                                     
[build]   Warnings:  1 packages succeeded with warnings.                       
[build]   Abandoned: None.                                                     
[build]   Failed:    None.                                                     
[build] Runtime: 3 minutes and 38.6 seconds total.                             
[build] Note: Workspace packages have changed, please re-source setup files to use them.

**Comment by tcies** [comment]
@yanjundream @Gaoee thanks for your initiative in resolving this! Just fixed the XMLs and updated the README . @ccs-ros I'm actually not sure whether suitesparse is really needed in dslam_open , please let me know if any issue pops up that would suggest that.
